# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, ubuntu-20.04, ubuntu-18.04, self-hosted, macos-11, macos-12, windows-2022, windows-2019]
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '18'
        distribution: 'temurin'
        cache: maven

    - name: Print tar version
      run: |
        tar --version
        zstd --version

    - name: Cache Maven repository
      uses: pdotl/cache@5b3cfe3a4da38d20fb0128ac5c32834c4add759c
      with:
        path: ~/.m2/repository
        key: ${{ matrix.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ matrix.os }}-maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
